Build from OpenAPI v3.0.1
XeroAPI/xero-node pull request #673
Opened 2024-02-12 12:12 UTC by thomas-anu

Fixes Payments API does not parse returned Warnings property

2024-02-12 12:21 UTC, sangeet-joy-tw requested changes

2024-02-12 12:21 UTC, sangeet-joy-tw commented on src/gen/api/accountingApi.ts
>   * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
here the version is still 5.0.1. need to be 5.0.2

2024-02-12 12:21 UTC, sangeet-joy-tw commented on src/gen/api/filesApi.ts
>   * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
here also the version is 5.0.1 which needs to be 5.0.2

2024-02-15 11:02 UTC, manishT72 commented
This is already taken care by https://github.com/XeroAPI/xero-node/pull/671

2024-02-15 11:02 UTC, closed without merging